on: [push]

jobs:
  render:
    runs-on: ubuntu-latest
    name: Render obsidian vault
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Render Action
        uses: ./.github/actions/render-action
        id: render
        with:
          vault-location: ./Notes
          vault-subdirectory: "/Dungeon World"
